<?php

namespace Compo\NewsBundle\Repository;

/**
 * NewsTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTagRepository extends \Doctrine\ORM\EntityRepository
{
}
