sonata_page:
    templates:
        2columns:
            containers:
                 content:
                     blocks:
                        - compo_articles.block.service.articles_last
        default:
            containers:
                 content:
                     blocks:
                        - compo_articles.block.service.articles_last