#
# more information can be found here https://sonata-project.org/bundles/formatter
#
sonata_formatter:
    formatters:
        #text:
        #    service: sonata.formatter.text.text
        #    extensions:
        #        - sonata.formatter.twig.control_flow
        #        - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig

        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'

# This section can be used to include the SonataMediaBundle with CKEDITOR
#  => https://sonata-project.org/bundles/media/master/doc/reference/extra.html#ckeditor-integration
#  there is also a configuration in the sonata_formatter section (see sonata_formatter.yml)
ivory_ck_editor:
    plugins:
        wpmore:
            path:     "/bundles/compocore/wpmore/"
            filename: "plugin.js"
    default_config: default
    configs:
        default:
            title: false
            toolbarStartupExpanded : false
            allowedContent: true
            extraAllowedContent: '*{*}'
            toolbar: "my_toolbar_1"
            extraPlugins: 'wpmore,fakeobjects'
            enterMode: "CKEDITOR.ENTER_P"
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                hide_context: true
                context: image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                hide_context: true
                context: file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: image # Optional, to upload in a custom context
    toolbars:
        configs:
            my_toolbar_1: [ "@document", "@wpmore", "@clipboard" , "@editing", "@basicstyles", "@paragraph", "@links", "@insert", "@styles", "@colors", "@tools" ]
        items:
            document: [ "Source", "-", "Save" ]
            wpmore:     [ "WPMore" ]
            clipboard:      [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ]

            editing:      [ 'Find','Replace','-','SelectAll' ]
            basicstyles:     [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            paragraph:     [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv', '-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ]
            links:     [ 'Link','Unlink','Anchor' ]
            insert:     [ 'Image','Table','HorizontalRule','SpecialChar','PageBreak','Iframe' ]
            styles:     [ 'Styles','Format','Font','FontSize' ]
            colors:    [ 'TextColor','BGColor' ]
            tools:    [ 'Maximize', 'ShowBlocks' ]

