sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      "Compo Standard"
    title_logo: "/bundles/compocore/images/compo_logo.png"



    options:
        html5_validate: true # does not use html5 validation
        pager_links: 5        # pager max links to display
        use_select2:    true # disable select2
        lock_protection: false
        form_type: horizontal
        sort_admins:          true
        confirm_exit:         true
        use_icheck:           true
        use_stickyforms:      true
        title_mode:           "single_image"

    persist_filters:      false
    show_mosaic_button:   false

    templates:
        layout:  CompoSonataAdminBundle::standard_layout_compo.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        list:    CompoSonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks: []
        groups: []

    extensions:
        compo.sonata.admin.tabmenu.extension:
            instanceof:
                - \Sonata\AdminBundle\Admin\Admin

        compo_seo.seo.extension:
            implements:
                - \Compo\SeoBundle\Extension\SeoExtensionInterface

    assets:
        javascripts:
            - assetic/sonata_admin_vendor_js.js
            - assetic/sonata_admin_core_js.js
            - assetic/sonata_admin_js.js

            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js

            - bundles/composonataadmin/js/nestedSortable.js

            - bundles/composonataadmin/js/admin.js


        stylesheets:
            - assetic/sonata_admin_vendor_css.css
            - assetic/sonata_admin_core_css.css
            - assetic/sonata_admin_css.css

            - bundles/composonataadmin/css/admin.css
            - bundles/composonataadmin/css/tree.css

sonata_doctrine_orm_admin:
    templates:
        form:
            - "CompoSonataAdminBundle::SonataDoctrineORMAdminBundle/Form/form_admin_fields.html.twig"

    audit:
        force: true
