parameters:
    locale: "ru"

    translator.class: Compo\CoreBundle\Translation\FallbackTranslator

    sonata.seo.page.default.class: Compo\SeoBundle\Seo\SeoPage

    sonata.page.block.breadcrumb.class: Compo\Sonata\PageBundle\Block\BreadcrumbBlockService

    sonata.page.service.default.class: Compo\Sonata\PageBundle\Page\Service\DefaultPageService
    sonata.page.manager.page.class: Compo\Sonata\PageBundle\Entity\PageManager

    sonata.page.admin.page.class: Compo\Sonata\PageBundle\Admin\PageAdmin
    sonata.page.admin.site.class: Compo\Sonata\PageBundle\Admin\SiteAdmin
    sonata.page.admin.block.class: Compo\Sonata\PageBundle\Admin\BlockAdmin
    sonata.page.admin.shared_block.class: Compo\Sonata\PageBundle\Admin\SharedBlockAdmin

    sonata.user.admin.user.class: Compo\Sonata\UserBundle\Admin\UserAdmin
    sonata.user.admin.group.class: Compo\Sonata\UserBundle\Admin\GroupAdmin

    sonata_user.google_authenticator.server:  compo-standard.localhost.ru

    sonata.media.admin.media.class: Compo\Sonata\MediaBundle\Admin\MediaAdmin

    sonata.formatter.block.formatter.class: Compo\Sonata\FormatterBundle\Block\FormatterBlockService
    sonata.block.service.text.class: Compo\Sonata\BlockBundle\Block\Service\TextBlockService

    sylius.settings.form_factory.class: Compo\CoreBundle\Form\Factory\SettingsFormFactory

    fos_elastica.property_accessor.class: Compo\CoreBundle\PropertyAccess\QuietPropertyAccessor

    router.request_context.host: '%server_name%'
    router.request_context.scheme: '%server_scheme%'
    router.request_context.base_url: ''

compo_core:
    theme:
        name: "comporu/default"

services:
    compo_core.block.service.admin_stats:
        class: Compo\CoreBundle\Block\AdminStatsBlockService
        arguments: ["compo_core.block.service.admin_stats", "@templating"]
        parent: compo_core.abstract_container_aware
        tags:
            - { name: sonata.block }

    compo_core.block.service.admin_custom_stats:
        class: Compo\CoreBundle\Block\AdminCustomStatsBlockService
        arguments: ["compo_core.block.service.admin_custom_stats", "@templating"]
        parent: compo_core.abstract_container_aware
        tags:
            - { name: sonata.block }

    compo_core.block.service.date_stats_admin:
        class: Compo\CoreBundle\Block\DateStatsAdminBlockService
        arguments: ["compo_core.block.service.date_stats_admin", "@templating"]
        parent: compo_core.abstract_container_aware
        tags:
            - { name: sonata.block }

doctrine:
    # ...
    orm:
        # ...
        entity_managers:
            default:
                mappings:
                    CompoSonataImportBundle: ~

compo_sonata_import:
    mappings:
    #   - { name: center_point, class: compo.form_format.point}
    #   - { name: city_autocomplete, class: compo.form_format.city_pa}
        - { name: date, class: doctrs.type.datetime}
        - { name: datetime, class: doctrs.type.datetime}
        - { name: boolean, class: doctrs.type.boolean}
        - { name: integer, class: doctrs.type.integer}
        - { name: entity, class: doctrs.type.entity}
        - { name: choice, class: doctrs.type.entity}
    upload_dir: '%kernel.root_dir%/../web/uploads/import'
    class_loaders:
        - { name: XLS, class: Compo\SonataImportBundle\Loaders\XlsFileLoader}
        - { name: CSV, class: Compo\SonataImportBundle\Loaders\CsvFileLoader}

    encode:
        default: utf8
        list:
            - cp1251
            - utf8
            - koir8
