imports:
    - { resource: framework.yml }
    - { resource: doctrine.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: swiftmailer.yml }
    - { resource: twig.yml }

    - { resource: simple_things_entity_audit.yml }
    - { resource: mopa_bootstrap.yml }
    - { resource: knp_paginator.yml }
    - { resource: jms.yml }
    - { resource: sylius.yml }

    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    - { resource: fos/fos_elastica.yml }
    - { resource: fos/fos_js_routing.yml }

    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }
    - { resource: sonata/sonata_dashboard.yml }

    - { resource: compo.yml }


