framework:
    esi: { enabled: true }
    translator:      { enabled: true, fallbacks: ["en"] }
    secret:          '%env(FRAMEWORK_SECRET)%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:                    true
    csrf_protection:         true

    validation:
        enabled: true
        enable_annotations: true

    serializer:
        enabled: true
        enable_annotations: true

    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
        #upsave_path:           "%kernel.root_dir%/cache/sessions"
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/'
        cookie_domain: "%env(COOKIE_DOMAIN)%"
        cookie_lifetime:  217728000
        cookie_httponly:  true

    fragments:       ~
    http_method_override: true

    assets:
        base_path: '/'

    cache:
        app: cache.adapter.apcu
        system: cache.adapter.apcu

        default_memcached_provider: "memcached://localhost:11211"

#        pools:
#            serializer:
#                adapter: cache.system

    php_errors:
        log: true
