nelmio_api_doc:
    resource:     "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /doc

sonata_api_media:
    type:         rest
    prefix:       /media
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

sonata_api_notification:
    type:         rest
    prefix:       /notification
    resource:     "@SonataNotificationBundle/Resources/config/routing/api.xml"

sonata_api_page:
    type:         rest
    prefix:       /page
    resource:     "@SonataPageBundle/Resources/config/routing/api.xml"

sonata_api_user:
    type:         rest
    prefix:       /user
    resource:     "@SonataUserBundle/Resources/config/routing/api.xml"
