services:
  gedmo.listener.softdeleteable:
      class: Gedmo\SoftDeleteable\SoftDeleteableListener
      tags:
          - { name: doctrine.event_subscriber, connection: default }
      calls:
          - [ setAnnotationReader, [ '@annotation_reader' ] ]

  gedmo.listener.tree:
      class: Gedmo\Tree\TreeListener
      tags:
          - { name: doctrine.event_subscriber, connection: default }
      calls:
          - [ setAnnotationReader, [ '@annotation_reader' ] ]

  twig.text_extension:
      class: Twig_Extensions_Extension_Text
      tags:
          - name: twig.extension

  compo.sonata.admin.tabmenu.extension:
      class: Compo\Sonata\AdminBundle\Extension\TabMenuExtension
      tags:
          - { name: sonata.admin.extension, global: true }

  sonata.seo.page.default:
      class: Compo\SeoBundle\Seo\SeoPage
      parent: compo_core.abstract_container_aware

  sonata.user.editable_role_builder:
      class: Compo\Sonata\UserBundle\Security\EditableRolesBuilder
      arguments: ["@security.token_storage", "@security.authorization_checker", "@sonata.admin.pool", "%security.role_hierarchy.roles%"]


#  security.acl.permission.map:
#      class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

