swiftmailer:
  default_mailer: 'mailer'
  mailers:
    mailer:
      transport: "%mailer_transport%"
      host:      "%mailer_host%"
      username:  "%mailer_user%"
      password:  "%mailer_password%"
      encryption: "ssl"
      auth_mode: "plain"
      port: "465"

#      spool:
#        type: file
#        path: '%kernel.project_dir%/var/spool'
