swiftmailer:
  default_mailer: 'mailer'
  mailers:
    mailer:
      transport: "%env(MAILER_TRANSPORT)%"
      host:      "%env(MAILER_HOST)%"
      username:  "%env(MAILER_USER)%"
      password:  "%env(MAILER_PASSWORD)%"
      encryption: "ssl"
      auth_mode: "plain"
      port: "465"

#      spool:
#        type: file
#        path: '%kernel.project_dir%/var/spool'
