language: php
sudo: false

addons:
  apt:
    update: true
    packages:
      # Needed for `xmllint`.
      - libxml2-utils
      - yamllint

cache:
  directories:
    - $HOME/.composer/cache/files
#    - $HOME/symfony-bridge/.phpunit

# env:
#  global:
#    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
#    - SYMFONY_PHPUNIT_VERSION="6.3"

dist: bionic

matrix:
  fast_finish: true
  include:
    - php: 7.2
#    - php: nightly
#  allow_failures:
#    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
#  - npm install -g bower
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - pip install -r docs/requirements.txt --user
  - mkdir --parents "${HOME}/bin"
  - wget "http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar" --output-document="${HOME}/bin/php-cs-fixer"
  - chmod u+x "${HOME}/bin/php-cs-fixer"
  - composer global require sllh/composer-lint:@stable --prefer-dist --no-interaction
  - wget "https://phar.phpunit.de/phpunit-5.7.phar" --output-document="${HOME}/bin/phpunit"
  - chmod u+x "${HOME}/bin/phpunit"
  - composer update --no-progress --no-interaction --no-suggest


script:
  # this checks that the YAML config files contain no syntax errors
  #- ./bin/console lint:yaml src

  # this checks that the Twig template files contain no syntax errors
  #- ./bin/console lint:twig src

  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock

  # this checks that the composer.json and composer.lock files are valid
  # --strict
  - composer validate

  # this checks that Doctrine's mapping configurations are valid
  #- ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

  - phpunit -c phpunit.xml.dist

  # this checks that the source code follows the Symfony Code Syntax rules
  - php-cs-fixer fix --diff --dry-run -v

  - cd docs && sphinx-build -W -b html -d _build/doctrees . _build/html
