services:
    compo_redirect.listener.redirect:
        parent: compo_core.abstract_container_aware
        class: Compo\RedirectBundle\Listener\RedirectListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 500 }

    compo_redirect.admin.redirect:
        class: Compo\RedirectBundle\Admin\RedirectAdmin
        arguments: [~, Compo\RedirectBundle\Entity\Redirect, CompoRedirectBundle:RedirectAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: redirect }
