services:
    compo_banner.admin.banner:
        class: Compo\BannerBundle\Admin\BannerAdmin
        arguments: [~, Compo\BannerBundle\Entity\Banner, CompoBannerBundle:BannerAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: banner }
        calls:
            - [ addChild, ['@compo_banner.admin.banner_item']]

    compo_banner.block.service.banner:
        class: Compo\BannerBundle\Block\BannerBlockService
        arguments: ["compo_banner.block.service.banner", "@templating"]
        tags:
            - { name: sonata.block }
        calls:
            - [ setContainer, ['@service_container']]

    compo_banner.admin.banner_item:
        class: Compo\BannerBundle\Admin\BannerItemAdmin
        arguments: [~, Compo\BannerBundle\Entity\BannerItem, CompoBannerBundle:BannerItemAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: banner_item }
