sonata_page:
    templates:
        default:
            containers:
                 header:
                     blocks:
                        - compo_banner.block.service.banner

                 content_top:
                     blocks:
                        - compo_banner.block.service.banner

                 content:
                     blocks:
                        - compo_banner.block.service.banner

                 content_bottom:
                     blocks:
                        - compo_banner.block.service.banner
                 footer:
                     blocks:
                        - compo_banner.block.service.banner

