<?php

/*
 * This file is part of the CompoSymfonyCms package.
 * (c) Compo.ru <info@compo.ru>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Compo\Sonata\PageBundle;

use Compo\Sonata\PageBundle\DependencyInjection\Compiler\AuditCompilerPass;
use Compo\Sonata\PageBundle\DependencyInjection\Compiler\ChildAdminCompilerPass;
use Compo\Sonata\PageBundle\DependencyInjection\Compiler\ExceptionListenerCompilerPass;
use Compo\Sonata\PageBundle\DependencyInjection\Compiler\PageServiceCompilerPass;
use Symfony\Component\DependencyInjection\Compiler\PassConfig;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * This file has been generated by the EasyExtends bundle ( https://sonata-project.org/easy-extends ).
 *
 * References :
 *   bundles : http://symfony.com/doc/current/book/bundles.html
 */
class CompoSonataPageBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataPageBundle';
    }

    /**
     * @param ContainerBuilder $container
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new ExceptionListenerCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
        $container->addCompilerPass(new PageServiceCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
        $container->addCompilerPass(new ChildAdminCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
        $container->addCompilerPass(new AuditCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
    }
}
