fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    from_email:
        address:        noreply@example.com
        sender_name:    Demo App

    # if you change the class configuration, please also alter the sonata_user.yml file
    user_class:        Compo\Sonata\UserBundle\Entity\User

    group:
        group_class:   Compo\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager
