fos_elastica:
    clients:
        default:
            host:                               127.0.0.1
            port:                               9200

    indexes:
        main:
            settings:
                number_of_shards: 5
                refresh_interval: "5s"
                index:
                    requests:
                        cache:
                            enable: true
                    analysis:
                        analyzer:
                            default_search:
                                alias: [search_ru]
                                type: custom
                                tokenizer: standard
                                filter: [stopwords_ru, stop, custom_word_delimiter, lowercase, russian_morphology, english_morphology]
                                char_filter: [ru]

                        char_filter:
                            ru:
                                type: mapping
                                mappings: ['Ё=>Е', 'ё=>е']
                            qwerty:
                                type: mapping
                                mappings: ['й=>q', 'ц=>w', 'у=>e', 'к=>r', 'е=>t', 'н=>y', 'г=>u', 'ш=>i', 'щ=>o', 'з=>p', 'х=>[', 'ъ=>]', 'ф=>a', 'ы=>s', 'в=>d', 'а=>f', 'п=>g', 'р=>h', 'о=>j', 'л=>k', 'д=>l', 'ж=>;', "э=>'", 'я=>z', 'ч=>x', 'с=>c', 'м=>v', 'и=>b', 'т=>n', 'ь=>m', 'б=>,', 'ю=>.', '.=>/']

                        tokenizer:
                            nGram:
                                type: nGram
                                min_gram: 4
                                max_gram: 20
                        filter:
                            stopwords_ru:
                                type: stop
                                stopwords: [а,без,более,бы,был,была,были,было,быть,в,вам,вас,весь,во,вот,все,всего,всех,вы,где,да,даже,для,до,его,ее,если,есть,еще,же,за,здесь,и,из,или,им,их,к,как,ко,когда,кто,ли,либо,мне,может,мы,на,надо,наш,не,него,нее,нет,ни,них,но,ну,о,об,однако,он,она,они,оно,от,очень,по,под,при,с,со,так,также,такой,там,те,тем,то,того,тоже,той,только,том,ты,у,уже,хотя,чего,чей,чем,что,чтобы,чье,чья,эта,эти,это,я]
                                ignore_case: true
                            custom_word_delimiter:
                                type: word_delimiter
                                # "PowerShot" ⇒ "Power" "Shot", части одного слова становятся отдельными токенами
                                generate_word_parts: true
                                generate_number_parts: true  # "500-42" ⇒ "500" "42"
                                catenate_words: true  # "wi-fi" ⇒ "wifi"
                                catenate_numbers: false  # "500-42" ⇒ "50042"
                                catenate_all: true  # "wi-fi-4000" ⇒ "wifi4000"
                                split_on_case_change: true  # "PowerShot" ⇒ "Power" "Shot"
                                preserve_original: true  # "500-42" ⇒ "500-42" "500" "42"
                                split_on_numerics: false  # "j2se" ⇒ "j" "2" "se"
                            latin_transform:
                                type: icu_transform
                                id: "Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC"



            index_name: "%fos_elastica_index_name%"

            client:                             default