fos_elastica:
    clients:
        default:
            host: "%env(FOS_ELASTICA_HOST)%"
            port: "%env(FOS_ELASTICA_PORT)%"

    indexes:
        main:
            client: default
            index_name: "%env(FOS_ELASTICA_INDEX_NAME)%"

            settings:
                number_of_shards: 1
                number_of_replicas: 0
                refresh_interval: "5s"
                max_result_window: 100000

                index:
                    requests:
                        cache:
                            enable: true
                    queries:
                        cache:
                            enabled: true
                    analysis:
                        analyzer:
                            default:
                                type: custom
                                char_filter: [compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology
                                    - autocomplete_filter

                            default_raw:
                                type: custom
                                char_filter: [compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop


                            default_search:
                                type: custom
                                char_filter: [compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology



                            default_search_compo_qwerty:
                                type: custom
                                char_filter: [compo_qwerty, compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology

                            default_search_compo_qwerty_revert:
                                type: custom
                                char_filter: [compo_qwerty_revert, compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology

                            phonetic_search:
                                type: custom
                                char_filter: [compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology
                                    - compo_phonetic_english
                                    - compo_phonetic_cyrillic

                            phonetic_search_qwerty:
                                type: custom
                                char_filter: [compo_qwerty, compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology
                                    - compo_phonetic_english
                                    - compo_phonetic_cyrillic

                            phonetic_search_qwerty_revert:
                                type: custom
                                char_filter: [compo_qwerty_revert,compo_ru]
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - compo_word_delimiter
                                    - compo_stop_russian_custom
                                    - stop
                                    - russian_morphology
                                    - english_morphology
                                    - compo_phonetic_english
                                    - compo_phonetic_cyrillic
                        tokenizer:
                            compo_ngram_search_ru:
                                type: nGram
                                min_gram: 3
                                max_gram: 20
                        filter:
                            compo_stop_russian:
                                type: stop
                                ignore_case: true
                                language: "_russian_"

                            compo_stop_russian_custom:
                                type: stop
                                stopwords: [а,без,более,бы,был,была,были,было,быть,в,вам,вас,весь,во,вот,все,всего,всех,вы,где,да,даже,для,до,его,ее,если,есть,еще,же,за,здесь,и,из,или,им,их,к,как,ко,когда,кто,ли,либо,мне,может,мы,на,надо,наш,не,него,нее,нет,ни,них,но,ну,о,об,однако,он,она,они,оно,от,очень,по,под,при,с,со,так,также,такой,там,те,тем,то,того,тоже,той,только,том,ты,у,уже,хотя,чего,чей,чем,что,чтобы,чье,чья,эта,эти,это,я]
                                ignore_case: true

                            compo_word_delimiter:
                                type: word_delimiter
                                # "PowerShot" ⇒ "Power" "Shot", части одного слова становятся отдельными токенами
                                generate_word_parts: true
                                generate_number_parts: true  # "500-42" ⇒ "500" "42"
                                catenate_words: true  # "wi-fi" ⇒ "wifi"
                                catenate_numbers: false  # "500-42" ⇒ "50042"
                                catenate_all: true  # "wi-fi-4000" ⇒ "wifi4000"
                                split_on_case_change: true  # "PowerShot" ⇒ "Power" "Shot"
                                preserve_original: true  # "500-42" ⇒ "500-42" "500" "42"
                                split_on_numerics: false  # "j2se" ⇒ "j" "2" "se"

                            latin_transform:
                                type: icu_transform
                                id: "Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC"

                            compo_phonetic_cyrillic:
                                type: "phonetic"
                                encoder: "beidermorse"
                                rule_type: "approx"
                                name_type: "generic"
                                languageset: ["cyrillic"]

                            compo_phonetic_english:
                                type: "phonetic"
                                encoder: "beidermorse"
                                rule_type: "approx"
                                name_type: "generic"
                                languageset: ["english"]

                            compo_snowball_russian:
                                type: "snowball"
                                encoder: "Russian"

                            autocomplete_filter:
                                type: "nGram"
                                encoder: "Russian"
                                min_gram: 3
                                max_gram: 20

                        char_filter:
                            compo_ru:
                                type: mapping
                                mappings: ['Ё=>Е', 'ё=>е', 'Й=>и', 'и=>и']
                            compo_qwerty:
                                type: mapping
                                mappings:
                                    - 'й=>q'
                                    - 'ц=>w'
                                    - 'у=>e'
                                    - 'к=>r'
                                    - 'е=>t'
                                    - 'н=>y'
                                    - 'г=>u'
                                    - 'ш=>i'
                                    - 'щ=>o'
                                    - 'з=>p'
                                    - 'х=>['
                                    - 'ъ=>]'
                                    - 'ф=>a'
                                    - 'ы=>s'
                                    - 'в=>d'
                                    - 'а=>f'
                                    - 'п=>g'
                                    - 'р=>h'
                                    - 'о=>j'
                                    - 'л=>k'
                                    - 'д=>l'
                                    - 'ж=>;'
                                    - "э=>'"
                                    - 'я=>z'
                                    - 'ч=>x'
                                    - 'с=>c'
                                    - 'м=>v'
                                    - 'и=>b'
                                    - 'т=>n'
                                    - 'ь=>m'
                                    - 'б=>,'
                                    - 'ю=>.'
                            compo_qwerty_revert:
                                type: mapping
                                mappings:
                                    - 'q=>й'
                                    - 'w=>ц'
                                    - 'e=>у'
                                    - 'r=>к'
                                    - 't=>е'
                                    - 'y=>н'
                                    - 'u=>г'
                                    - 'i=>ш'
                                    - 'o=>щ'
                                    - 'p=>з'
                                    - '[=>х'
                                    - ']=>ъ'
                                    - 'a=>ф'
                                    - 's=>ы'
                                    - 'd=>в'
                                    - 'f=>а'
                                    - 'g=>п'
                                    - 'h=>р'
                                    - 'j=>о'
                                    - 'k=>л'
                                    - 'l=>д'
                                    - ';=>ж'
                                    - "'=>э"
                                    - 'z=>я'
                                    - 'x=>ч'
                                    - 'c=>с'
                                    - 'v=>м'
                                    - 'b=>и'
                                    - 'n=>т'
                                    - 'm=>ь'
                                    - ',=>б'
                                    - '.=>ю'
