<?php

namespace Compo\SeoBundle\Repository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoPageRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{

}
