<?php

namespace Compo\SeoBundle\Repository;

use Compo\SeoBundle\Entity\SeoPage;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoPageRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{

}
