compo_sonata_import:
    upload_dir: %kernel.root_dir%/../web/uploads/import
    class_loaders:
        - { name: CSV, class: Compo\SonataImportBundle\Loaders\CsvFileLoader}
        - { name: XLS, class: Compo\SonataImportBundle\Loaders\XlsFileLoader}
    encode:
        default: utf8
        list:
            - cp1251
            - utf8
