<?php

namespace Compo\PageCodeBundle\Repository;

/**
 * PageCodeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCodeRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{
    public function getLayoutChoices()
    {
        return [
            'До </head>' => 'pre_head_end',
            'До </body>' => 'pre_body_end',
        ];
    }
}
