<?php

/*
 * This file is part of the CompoSymfonyCms package.
 * (c) Compo.ru <info@compo.ru>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Compo\PageCodeBundle\Repository;

/**
 * PageCodeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCodeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getLayoutChoices()
    {
        return [
            'До </head>' => 'pre_head_end',
            'До </body>' => 'pre_body_end',
        ];
    }
}
