services:
    compo_seo.seo.extension:
        class: Compo\SeoBundle\Extension\SeoExtension
        tags:
            - { name: sonata.admin.extension, target: compo_product.admin.product }

    compo_seo.form.type.seo_vars:
        class: Compo\SeoBundle\Form\SeoVarsType
        tags:
            - { name: form.type }

    compo_seo.seo.twig.extension:
        class: Compo\SeoBundle\Twig\Extension\SeoExtension
        parent: compo_core.abstract_container_aware
        tags:
            - { name: twig.extension }