assetic:
    assets:
        sonata_front_vendor_core_js:
            inputs:
                - "bundles/compocore/vendor/jquery/dist/jquery.js"
                - "bundles/compocore/vendor/jquery-ui/jquery-ui.js"
                - "bundles/compocore/vendor/bootstrap/dist/js/bootstrap.js"

        sonata_front_vendor_js:
            inputs: []

        sonata_front_js:
            inputs: []

        sonata_front_vendor_core_css:
            inputs:
                - "bundles/compocore/vendor/jquery-ui/themes/redmond/jquery-ui.min.css"
                - "bundles/compocore/vendor/bootstrap/dist/css/bootstrap.min.css"
                - "bundles/compocore/vendor/fontawesome/css/font-awesome.min.css"

        sonata_front_vendor_css:
            inputs: []

        sonata_front_css:
            inputs: []