<?php

namespace Compo\MenuBundle\Entity;

use Compo\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
}
