<?php

namespace Compo\MenuBundle\Entity;

use Compo\Sonata\AdminBundle\Repository\TreeTrait;

/**
 * MenuItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends \Gedmo\Tree\Entity\Repository\NestedTreeRepository
{
    use TreeTrait;
}
