<?php

namespace Compo\MenuBundle\Entity;

use Compo\Sonata\AdminBundle\Entity\TreeRepositoryTrait;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends \Gedmo\Tree\Entity\Repository\NestedTreeRepository
{
    use TreeRepositoryTrait;

}
