<?php

namespace Compo\MenuBundle\Entity;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getMenuChoices()
    {
        $choices = array();

        /** @var Menu[] $items */
        $items = $this->findBy(array(), array('name' => 'ASC'));

        foreach ($items as $item) {
            $choices[$item->getId()] = $item->getName();
        }

        return $choices;
    }
}
