services:
    compo_menu.admin.menu:
        class: Compo\MenuBundle\Admin\MenuAdmin
        arguments: [~, Compo\MenuBundle\Entity\Menu, CompoMenuBundle:MenuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: menu, label_translator_strategy: sonata.admin.label.strategy.underscore }
        calls:
            - [ addChild, ['@compo_menu.admin.menu_item']]

    compo_menu.block.service.menu:
        class: Compo\MenuBundle\Block\MenuBlockService
        arguments: ["compo_menu.block.service.menu", "@templating"]
        tags:
            - { name: sonata.block }
        calls:
            - [ setContainer, ['@service_container']]

    compo_menu.admin.menu_item:
        class: Compo\MenuBundle\Admin\MenuItemAdmin
        arguments: [~, Compo\MenuBundle\Entity\MenuItem, CompoMenuBundle:MenuItemAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: menu_item, label_translator_strategy: sonata.admin.label.strategy.underscore }
