<?php

namespace Compo\AdvantagesBundle\Entity;

/**
 * AdvantagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvantagesChoices()
    {
        $choices = array();

        /** @var Advantages[] $items */
        $items = $this->findBy(array(), array('name' => 'ASC'));

        foreach ($items as $item) {
            $choices[$item->getId()] = $item->getName();
        }

        return $choices;
    }
}
