services:
#    compo_sms_provider.example:
#        class: Compo\SmsProviderBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    compo_sms_provider.admin.sms_provider:
        class: Compo\SmsProviderBundle\Admin\SmsProviderAdmin
        arguments: [~, Compo\SmsProviderBundle\Entity\SmsProvider, CompoSmsProviderBundle:SmsProviderAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: sms_provider, label_translator_strategy: sonata.admin.label.strategy.underscore }
