<?php

namespace Compo\ContactsBundle\Repository;

use Compo\ContactsBundle\Entity\Contacts;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{

}
