<?php

namespace Compo\SmsProviderBundle\Repository;

use Compo\SmsProviderBundle\Entity\SmsProvider;

/**
 * SmsProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsProviderRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{

}
