<?php

namespace Compo\AdvantagesBundle\Entity;

use Compo\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * AdvantagesItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantagesItemRepository extends EntityRepository
{
}