<?php

namespace Compo\AdvantagesBundle\Entity;

use Compo\Sonata\AdminBundle\Entity\TreeRepositoryTrait;

/**
 * AdvantagesItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantagesItemRepository extends \Doctrine\ORM\EntityRepository
{

}
