<?php

namespace Compo\FeedbackBundle\Entity;

use Compo\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackTagRepository extends EntityRepository
{
}
