bazinga_faker:
    orm: doctrine
    locale: ru_RU
    entities:
        Compo\ProductBundle\Entity\Product:
            number: 5
            custom_formatters:
                price:   { method: randomFloat, parameters: [2, 100, 100000] }
                priceOld:   { method: randomFloat, parameters: [2, 100, 100000] }
                priceOriginal:   { method: randomFloat, parameters: [2, 100, 100000] }
                priceOldOriginal:   { method: randomFloat, parameters: [2, 100, 100000] }
                name: {method: text}