<?php

namespace Compo\NotificationBundle\Repository;

use Compo\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * NotificationEmailAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEmailAccountRepository extends EntityRepository
{
    /**
     * @return null
     */
    public function getDefaultId()
    {
        $currency = $this->findOneBy([], ['id' => 'ASC']);

        if ($currency) {
            return $currency->getId();
        }

        return null;
    }
}
