<?php

namespace Compo\NotificationBundle\Repository;

use Compo\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * NotificationEmailAccountRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSmsAccountRepository extends EntityRepository
{
    public function getDefaultId()
    {
        $currency = $this->findOneBy(array(), array('id' => 'ASC'));

        if ($currency) {
            return $currency->getId();
        }

        return null;
    }
}
