<?php

namespace Compo\NotificationBundle\Repository;

use Compo\NotificationBundle\Entity\NotificationEmail;

/**
 * NotificationEmailAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEmailAccountRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDefaultId()
    {
        $currency = $this->findOneBy(array(), array('id' => 'ASC'));

        if ($currency) {
            return $currency->getId();
        } else {
            return null;
        }
    }

    /**
     * @return array
     */
    public function getChoices()
    {
        $choices = array();

        /** @var [] $items */
        $items = $this->findBy(array(), array('name' => 'ASC'));

        foreach ($items as $item) {
            $choices[$item->getId()] = $item->getName();
        }

        return $choices;
    }
}
