<?php

namespace Compo\NotificationBundle\Repository;

/**
 * NotificationEmailRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSmsRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{
}
