sonata_admin:
    global_search:
        empty_boxes: hide

    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role
        # acl security information
        information:
            # Просмотр списка
            GUEST:    [VIEW, LIST]
            # Просмотр списка, Редактирование, Создание
            STAFF:    [VIEW, LIST, EDIT, CREATE]
            # Просмотр списка, Редактирование, Создание, Удаление, Корзина, Действия, Экспорт
            EDITOR:   [VIEW, LIST, EDIT, CREATE, DELETE, UNDELETE, OPERATOR, EXPORT]
            # Полный доступ
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [LIST, CREATE, DELETE, UNDELETE, OPERATOR, EXPORT, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      "Compo!"
    title_logo: "/bundles/compocore/images/compo_logo_simple.png"

    options:
        html5_validate: true # does not use html5 validation
        pager_links: 5        # pager max links to display
        use_select2:    true # disable select2
        lock_protection: false
        form_type: horizontal
        sort_admins:          true
        confirm_exit:         true
        use_icheck:           true
        use_stickyforms:      false
        title_mode:           "single_image"

    persist_filters:      false
    show_mosaic_button:   true

    templates:
        layout:  CompoSonataAdminBundle::standard_layout_compo.html.twig
        list:    CompoSonataAdminBundle:CRUD:list.html.twig
        history_revision_timestamp:     '@CompoSonataAdmin/CRUD/history_revision_timestamp.html.twig'
        tab_menu_template:  CompoSonataAdminBundle:Core:tab_menu_template_extend.html.twig

    dashboard:
        blocks: []
        groups:
            sonata_dashboard:
                label:           'Панель управления'
                label_catalogue: SonataDashboardBundle
                icon:            '<i class="fa fa-folder"></i>'
                items:
                    - sonata.dashboard.admin.dashboard
                    - route:        admin_sonata_dashboard_dashboard_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_DASHBOARD_ADMIN_DASHBOARD_SETTINGS]

            sonata.admin.group.news:
                label:           news
                label_catalogue: CompoNewsBundle
                icon:            '<i class="fa fa-newspaper-o"></i>'
                items:
                    - compo_news.admin.news
                    - compo_news.admin.news_tag
                    - route:        admin_compo_news_news_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_NEWS_ADMIN_NEWS_SETTINGS]

            sonata.admin.group.articles:
                label:           articles
                label_catalogue: CompoArticlesBundle
                icon:            '<i class="fa fa-file-text"></i>'
                items:
                    - compo_articles.admin.articles
                    - route:        admin_compo_articles_articles_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_ARTICLES_ADMIN_ARTICLES_SETTINGS]

            sonata.admin.group.faq:
                label:           faq
                label_catalogue: CompoFaqBundle
                icon:            '<i class="fa fa-question-circle-o"></i>'
                items:
                    - compo_faq.admin.faq
                    - route:        admin_compo_faq_faq_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_FAQ_ADMIN_FAQ_SETTINGS]

            sonata.admin.group.site_builder:
                label:           site
                label_catalogue: CompoCoreBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.site
                    - route:        admin_sonata_page_page_tree
                      label:        sonata_page_admin_page
                      roles: [ROLE_SUPER_ADMIN,ROLE_SONATA_PAGE_ADMIN_PAGE_LIST]
                    - sonata.page.admin.shared_block

                    - compo_page_code.admin.page_code
                    - compo_core.admin.settings
                    - compo_menu.admin.menu
                    - compo_banner.admin.banner
                    - compo_advantages.admin.advantages
                    - compo_contacts.admin.contacts
                    - compo_social.admin.social

            sonata.admin.group.feedback:
                label:           feedback
                label_catalogue: CompoFeedbackBundle
                icon:            '<i class="fa fa-envelope-o"></i>'
                items:
                    - compo_feedback.admin.feedback
                    - compo_feedback.admin.feedback_tag

            sonata.admin.group.notification:
                label:           notification
                label_catalogue: CompoNotificationBundle
                icon:            '<i class="fa fa-envelope-open"></i>'
                items:
                    - compo_notification.admin.notification_email_account
                    - compo_notification.admin.notification_email
                    - compo_notification.admin.notification_sms_account
                    - compo_notification.admin.notification_sms
                    - route:        admin_compo_notification_notificationemail_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_NOTIFICATION_ADMIN_NOTIFICATIONEMAIL_SETTINGS]

            sonata.admin.group.seo:
                label:           'SEO'
                label_catalogue: CompoCoreBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - compo_seo.admin.seo_page
                    - compo_redirect.admin.redirect
                    - route:        admin_compo_seo_seopage_settings
                      label:        'Настройки'
                      roles: [ROLE_SUPER_ADMIN,ROLE_COMPO_SEO_ADMIN_SEOPAGE_SETTINGS]


            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: CompoCoreBundle
                icon:            '<i class="fa fa-users"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.media.admin.media
                    - sonata.notification.admin.message


    extensions:
        compo.sonata.admin.tabmenu.extension:
            instanceof:
                - \Sonata\AdminBundle\Admin\AdminInterface

        compo_seo.seo.extension:
            implements:
                - \Compo\SeoBundle\Extension\SeoExtensionInterface

    assets:
        extra_javascripts:
            - bundles/compocore/ckeditor/ckeditor.js

            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js

            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/html/set.js

            - bundles/sonatadashboard/sonata-dashboard.back.js
            - bundles/sonatapage/sonata-page.back.js

            - vendor/seiyria-bootstrap-slider/dist/bootstrap-slider.js

            - vendor/codemirror/lib/codemirror.js
            - vendor/codemirror/addon/mode/overlay.js
            - vendor/codemirror/addon/mode/multiplex.js
            - vendor/codemirror/mode/xml/xml.js
            - vendor/codemirror/mode/htmlmixed/htmlmixed.js
            - vendor/codemirror/mode/twig/twig.js

            - vendor/datatable/media/js/jquery.dataTables.js
            - vendor/datatable/media/js/dataTables.bootstrap.js

            - vendor/highcharts/highstock.js
            - vendor/highcharts/modules/series-label.js
            - vendor/highcharts/modules/exporting.js

            - vendor/ilikenwf-nested-sortable/jquery.mjs.nestedSortable.js

            - bundles/compocore/js/functions.js

            - bundles/composonataadmin/js/admin.js
            - bundles/composonataadmin/js/setup_icheck.js
            - bundles/composonataadmin/js/highcharts_options.js
            - bundles/composonataadmin/js/add_list_fields.js
            - bundles/composonataadmin/js/stats.js
            - bundles/composonataadmin/js/select_all.js
            - bundles/composonataadmin/js/sidebar_toggle.js
            - bundles/composonataadmin/js/table_sortable.js
            - bundles/composonataadmin/js/code_mirror.js
            - bundles/composonataadmin/js/tab_menu.js
            - bundles/composonataadmin/js/btn_batch.js
            - bundles/composonataadmin/js/tree.js

            - bundles/compomenu/js/admin/menu.js

            - bundles/compomanufacture/js/admin/fill_manufacture_collection.js

            - bundles/compoorder/js/admin/update_order.js

            - bundles/compotagging/js/products_filter.js
            - bundles/compotagging/js/products_filter_admin.js
            - bundles/compotagging/js/onload.js

        extra_stylesheets:
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css

            - bundles/sonatapage/sonata-page.back.css
            - bundles/sonatadashboard/sonata-dashboard.back.css

            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css

            - vendor/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css
            - vendor/codemirror/lib/codemirror.css
            - vendor/datatable/media/css/dataTables.bootstrap.css

            - bundles/composonataadmin/css/admin.css
            - bundles/composonataadmin/css/list.css
            - bundles/composonataadmin/css/list_responsive.css
            - bundles/composonataadmin/css/form.css
            - bundles/composonataadmin/css/form_responsive.css
            - bundles/composonataadmin/css/settings.css
            - bundles/composonataadmin/css/select2.css
            - bundles/composonataadmin/css/icheckbox.css
            - bundles/composonataadmin/css/icheckbox_responsive.css
            - bundles/composonataadmin/css/media.css
            - bundles/composonataadmin/css/page.css
            - bundles/composonataadmin/css/features.css
            - bundles/composonataadmin/css/roles.css
            - bundles/composonataadmin/css/filter.css
            - bundles/composonataadmin/css/navbar.css
            - bundles/composonataadmin/css/navbar_responsive.css
            - bundles/composonataadmin/css/stats.css
            - bundles/composonataadmin/css/compare.css
            - bundles/composonataadmin/css/order.css
            - bundles/composonataadmin/css/logo.css
            - bundles/composonataadmin/css/tree.css
            - bundles/composonataadmin/css/code_mirror.css

            - bundles/compotagging/css/catalog_filter_admin.css


sonata_doctrine_orm_admin:
    templates:
        form:
            - "CompoSonataAdminBundle::SonataDoctrineORMAdminBundle/Form/form_admin_fields.html.twig"

    audit:
        force: false
