sonata_classification:
    class:
        tag:            Compo\Sonata\ClassificationBundle\Entity\Tag
        category:       Compo\Sonata\ClassificationBundle\Entity\Category
        context:        Compo\Sonata\ClassificationBundle\Entity\Context
        collection:     Compo\Sonata\ClassificationBundle\Entity\Collection
        media:          Compo\Sonata\MediaBundle\Entity\Media

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
                    CompoSonataClassificationBundle: ~
