<?php

namespace Compo\BannerBundle\Entity;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBannerChoices()
    {
        $choices = array();

        /** @var Banner[] $items */
        $items = $this->findBy(array(), array('name' => 'ASC'));

        foreach ($items as $item) {
            $choices[$item->getId()] = $item->getName();
        }

        return $choices;
    }
}
