<?php

namespace Compo\BannerBundle\Entity;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{

}
