<?php

namespace Compo\BannerBundle\Entity;

/**
 * BannerItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerItemRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{
}
