compo_seo:
    pages:
        - context: 'article_list'
          title: 'Статьи'
          metaKeyword: 'Статьи'
          metaDescription: 'Статьи'
          header: 'Статьи'
          description: ''
          descriptionAdditional: ''
          admin: 'compo_articles.admin.articles'

        - context: 'article_show'
          title: '{{ article.name }}'
          metaKeyword: '{{ article.name }}'
          metaDescription: '{{ article.name }}'
          header: '{{ article.header|default(article.name) }}'
          description: ''
          descriptionAdditional: ''
          admin: 'compo_articles.admin.articles'
