compo_articles_index:
    path:     /articles/
    defaults: { _controller: "CompoArticlesBundle:Articles:index" }
    methods:  GET

compo_articles_show_by_slug:
    path:     /articles/{slug}.html
    defaults: { _controller: "CompoArticlesBundle:Articles:showBySlug" }
    methods:  GET