services:
    compo_core.abstract_container_aware:
        abstract:  true
        calls:
            - [setContainer, ["@service_container"]]

    compo_core.translator.extractor:
        class: Compo\CoreBundle\Translation\AdminExtractor
        tags: [{name: jms_translation.extractor, alias: compo_admin}]
        arguments:
            - "@sonata.admin.pool"

    compo_core.twig_extension:
        class: Compo\CoreBundle\Twig\ColorExtension
        public: false
        tags:
            - { name: twig.extension }

    compo_core.twig.media_extension:
        class: Compo\CoreBundle\Twig\MediaExtension
        arguments: ["@sonata.media.pool", "@sonata.media.manager.media", "@liip_imagine.cache.manager", "@liip_imagine.filter.manager"]
        tags:
            - { name: twig.extension }

    compo_core.twig.show_more_extension:
        class: Compo\CoreBundle\Twig\ShowMoreExtension
        tags:
            - { name: twig.extension }

    compo_core.settings_schema.meta:
        class: Compo\CoreBundle\Settings\AdminSettingsSchema
        parent: compo_core.abstract_container_aware
        tags:
            - { name: "sylius.settings_schema", namespace: "compo_core_settings", alias: "compo_core_settings" }


    compo_core.admin.settings:
        class: Compo\CoreBundle\Admin\SettingsAdmin
        parent: compo_core.abstract_container_aware
        arguments: [~, Sylius\Bundle\SettingsBundle\Model\Settings, CompoCoreBundle:SettingsAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: core_settings, label_translator_strategy: sonata.admin.label.strategy.underscore }


    knp_paginator.subscriber.sliding_pagination:
        class: Compo\CoreBundle\Subscriber\SlidingPaginationSubscriber
        arguments: [{defaultPaginationTemplate: "%knp_paginator.template.pagination%", defaultSortableTemplate: "%knp_paginator.template.sortable%", defaultFiltrationTemplate: "%knp_paginator.template.filtration%", defaultPageRange: "%knp_paginator.page_range%"}]
        tags:
            - { name: knp_paginator.subscriber }
            - { name: kernel.event_listener, event: "kernel.request", method: "onKernelRequest" }

    compo_core.block.service.news_with_articles_last:
        class: Compo\CoreBundle\Block\NewsWithArticlesLastBlockService
        parent: compo_core.abstract_container_aware
        arguments: ["compo_core.block.service.news_with_articles_last", "@templating"]
        tags:
            - { name: sonata.block }

    compo_core.block.service.text_page:
            class: Compo\CoreBundle\Block\TextPageBlockService
            parent: compo_core.abstract_container_aware
            arguments: ["compo_core.block.service.text_page", "@templating"]
            tags:
                - { name: sonata.block }

    sonata.page.kernel.exception_listener:
        class: Compo\Sonata\PageBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -127   }
            - { name: monolog.logger, channel: request   }
        arguments:
            - "@sonata.page.site.selector"
            - "@sonata.page.cms_manager_selector"
            - "%kernel.debug%"
            - "@templating"
            - "@sonata.page.page_service_manager"
            - "@sonata.page.decorator_strategy"
            - {"404": "_page_internal_error_not_found", "500": "_page_internal_error_fatal"}
            - "@logger"


    compo_core.manager.theme:
        class: Compo\CoreBundle\Manager\ThemeManager
        parent: compo_core.abstract_container_aware

    compo_core.manager:
        class: Compo\CoreBundle\Manager\CoreManager
        parent: compo_core.abstract_container_aware


    sylius.theme.translation.translator:
        class: Compo\CoreBundle\Translation\ThemeTranslator
        arguments:
            - "@sylius.theme.translation.loader_provider"
            - "@sylius.theme.translation.resource_provider"
            - "@translator.selector"
            - "%kernel.default_locale%"
            - {"cache_dir": "%kernel.cache_dir%/translations", "debug": "%kernel.debug%"}


    quiet_property_accessor:
        class: Compo\CoreBundle\PropertyAccess\QuietPropertyAccessor

    my_model_to_elastica_transformer:
        class: FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer
        arguments: [[], "@event_dispatcher"]
        calls:
            - [setPropertyAccessor, ["@quiet_property_accessor"]]


