sonata_page:
    templates:

        default:
            containers:
                 header:
                     blocks:
                 content_top:
                     blocks:
                        - compo_contacts.block.service.feedback_form
                 content:
                     blocks:
                        - compo_contacts.block.service.contacts_main
                 content_bottom:
                     blocks:
