Compo\ContactsBundle\Entity\Contacts:
    type: entity
    table: contacts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        address:
            type: string
            length: 1024
            nullable: true
        worktime:
             type: string
             length: 1024
             nullable: true
        phone:
             type: string
             length: 255
             nullable: true
        email:
             type: string
             length: 255
             nullable: true
        bankprops:
             type: string
             length: 1024
             nullable: true
        walk_instruction:
             type: string
             length: 1024
             nullable: true
        car_instruction:
             type: string
             length: 1024
             nullable: true
        maps_code:
              type: string
              length: 255
              nullable: true
        cix:
              type: string
              length: 20
              nullable: true
        ciy:
              type: string
              ength: 20
              nullable: true