Compo\ContactsBundle\Entity\Contacts:
    type: entity
    table: contacts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
             type: string
             nullable: true
        address:
            type: text
            nullable: true
        worktime:
             type: text
             nullable: true
        phone:
             type: text
             nullable: true
        email:
             type: string
             length: 255
             nullable: true
        bankprops:
             type: text
             nullable: true
        walk_instruction:
             type: text
             nullable: true
        car_instruction:
             type: text
             nullable: true
        maps_code:
              type: string
              length: 255
              nullable: true
        cix:
              type: string
              length: 20
              nullable: true
        ciy:
              type: string
              ength: 20
              nullable: true
