sonata_page:
    templates:

        default:
            containers:
                 header:
                     blocks:
                        - compo_advantages.block.service.advantages

                 content_top:
                     blocks:
                        - compo_advantages.block.service.advantages

                 content:
                     blocks:
                        - compo_advantages.block.service.advantages

                 content_bottom:
                     blocks:
                        - compo_advantages.block.service.advantages
                 footer:
                     blocks:
                        - compo_advantages.block.service.advantages

