<?php

namespace Compo\RedirectBundle\Repository;

/**
 * RedirectRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends \Compo\CoreBundle\Doctrine\ORM\EntityRepository
{
}
