compo_notification:
    events:
        -
            name: "compo_feedback.callback_for_user"
            event: "compo_feedback.callback"
            recipient: "{{ feedback.email}}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.callback_for_admin"
            event: "compo_feedback.callback"
            recipient: "{{ compo_notification_email_settings.notification_email_recipient_default }}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.feedback_for_user"
            event: "compo_feedback.feedback"
            recipient: "{{ feedback.email}}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.feedback_for_admin"
            event: "compo_feedback.feedback"
            recipient: "{{ compo_notification_email_settings.notification_email_recipient_default }}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.write_to_director_for_user"
            event: "compo_feedback.write_to_director"
            recipient: "{{ feedback.email}}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.write_to_director_for_admin"
            event: "compo_feedback.write_to_director"
            recipient: "{{ compo_notification_email_settings.notification_email_recipient_default }}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.product_want_lower_cost_for_user"
            event: "compo_feedback.product_want_lower_cost"
            recipient: "{{ feedback.email}}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"

        -
            name: "compo_feedback.product_want_lower_cost_for_admin"
            event: "compo_feedback.product_want_lower_cost"
            recipient: "{{ compo_notification_email_settings.notification_email_recipient_default }}"
            subject: "CompoFeedbackBundle:Notification:Email/feedback_subject.html.twig"
            body: "CompoFeedbackBundle:Notification:Email/feedback_body.html.twig"
            help: "CompoFeedbackBundle:Notification:Email/feedback_help.html.twig"
            type: "email"
