compo_feedback:
    types:
        -
            type: 'compo_feedback.feedback'
            form: 'Compo\FeedbackBundle\Form\FeedbackFormType'
            template: 'CompoFeedbackBundle:Form:feedback.html.twig'

        -
            type: 'compo_feedback.write_to_director'
            form: 'Compo\FeedbackBundle\Form\WriteToDirectorFormType'
            template: 'CompoFeedbackBundle:Form:write_to_director.html.twig'

        -
            type: 'compo_feedback.callback'
            form: 'Compo\FeedbackBundle\Form\CallbackFormType'
            template: 'CompoFeedbackBundle:Form:callback.html.twig'