services:
    compo_feedback.admin.feedback:
        class: Compo\FeedbackBundle\Admin\FeedbackAdmin
        arguments: [~, Compo\FeedbackBundle\Entity\Feedback, CompoFeedbackBundle:FeedbackAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: feedback, label_translator_strategy: sonata.admin.label.strategy.underscore }

    compo_feedback.manager.feedback:
        class: Compo\FeedbackBundle\Manager\FeedbackManager
        arguments: [Compo\FeedbackBundle\Entity\Feedback, "@doctrine"]
        parent: compo_core.abstract_container_aware

    compo_feedback.settings.feedback:
        class: Compo\FeedbackBundle\Settings\FeedbackSettingsSchema
        parent: compo_core.abstract_container_aware
        tags:
            - { name: "sylius.settings_schema", namespace: "compo_feedback", alias: "compo_feedback" }

    compo_feedback.admin.feedback_tag:
        class: Compo\FeedbackBundle\Admin\FeedbackTagAdmin
        arguments: [~, Compo\FeedbackBundle\Entity\FeedbackTag, CompoFeedbackBundle:FeedbackTagAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: feedback_tag, label_translator_strategy: sonata.admin.label.strategy.underscore }

    compo_feedback.block.service.feedback_form:
            class:  Compo\FeedbackBundle\Block\FeedbackFormBlockService
            parent: compo_core.abstract_container_aware
            arguments: ["compo_contacts.block.service.feedback_form", "@templating"]
            tags:
                 - { name: sonata.block }

    compo_feedback.form.type.feedback:
        class: Compo\FeedbackBundle\Form\FeedbackFormType
        parent: compo_core.abstract_container_aware
        tags:
            - { name: form.type }

    compo_feedback.form.type.wrtite_to_director:
        class: Compo\FeedbackBundle\Form\WriteToDirectorFormType
        parent: compo_core.abstract_container_aware
        tags:
            - { name: form.type }