sonata_page:
    templates:
        2columns:
            containers:
                 header:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content_top:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 sidebar:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content_bottom:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 footer:
                     blocks:
                        - compo_feedback.block.service.feedback_form

        default:
            containers:
                 header:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content_top:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content:
                     blocks:
                        - compo_feedback.block.service.feedback_form
                 content_bottom:
                     blocks:
                        - compo_feedback.block.service.feedback_form