compo_news_index:
    path:     /
    defaults: { _controller: "CompoNewsBundle:News:index" }
    methods:  GET

compo_news_show_by_slug:
    path:     /{slug}.html
    defaults: { _controller: "CompoNewsBundle:News:showBySlug" }
    methods:  GET
