services:
    compo.sonata.admin.tabmenu.extension:
        class: Compo\Sonata\AdminBundle\Extension\TabMenuExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.list_fields.extension:
        class: Compo\Sonata\AdminBundle\Extension\ListFieldsExtension
        parent: compo_core.abstract_container_aware
        tags:
            - { name: sonata.admin.extension, global: true, priority: 200 }

    compo.sonata.admin.actions.extension:
        class: Compo\Sonata\AdminBundle\Extension\ActionsExtension
        tags:
            - { name: sonata.admin.extension, global: true, priority: 22 }

    compo.sonata.admin.extension.position:
        class: Compo\Sonata\AdminBundle\Extension\PositionExtension
        tags:
            - { name: sonata.admin.extension, global: true, priority: 21 }

    compo.sonata.admin.sortable.extension:
        class: Compo\Sonata\AdminBundle\Extension\SortableExtension
        tags:
            - { name: sonata.admin.extension, global: true, priority: 10 }

    compo.sonata.admin.alias.extension:
        class: Compo\Sonata\AdminBundle\Extension\AliasExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.body.extension:
        class: Compo\Sonata\AdminBundle\Extension\BodyExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.color.extension:
        class: Compo\Sonata\AdminBundle\Extension\ColorExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.description_additional.extension:
        class: Compo\Sonata\AdminBundle\Extension\DescriptionAdditionalExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.name.extension:
        class: Compo\Sonata\AdminBundle\Extension\NameExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.publication_at.extension:
        class: Compo\Sonata\AdminBundle\Extension\PublicationAtExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.views.extension:
        class: Compo\Sonata\AdminBundle\Extension\ViewsExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.extension.id:
        class: Compo\Sonata\AdminBundle\Extension\IdExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.extension.enabled:
        class: Compo\Sonata\AdminBundle\Extension\EnabledExtension
        tags:
            - { name: sonata.admin.extension, global: true }

    compo.sonata.admin.extension.description:
        class: Compo\Sonata\AdminBundle\Extension\DescriptionExtension
        tags:
            - { name: sonata.admin.extension, global: true }
        parent: compo_core.abstract_container_aware

    compo.sonata.admin.extension.without_image:
        class: Compo\Sonata\AdminBundle\Extension\WithoutImageExtension
        tags:
            - { name: sonata.admin.extension, global: true }
        parent: compo_core.abstract_container_aware

    compo.sonata.admin.extension.timestampable:
        class: Compo\Sonata\AdminBundle\Extension\TimestampableExtension
        tags:
            - { name: sonata.admin.extension, global: true }
        parent: compo_core.abstract_container_aware

    compo.sonata.admin.extension.properties:
        class: Compo\Sonata\AdminBundle\Extension\PropertiesExtension
        tags:
            - { name: sonata.admin.extension, global: true, priority: 100 }
        parent: compo_core.abstract_container_aware

    compo.sonata.admin.form.type.tree_selector:
        class: Compo\Sonata\AdminBundle\Form\Type\TreeSelectorType
        arguments: ["@property_accessor"]
        tags:
            - { name: form.type, alias: compo_tree_selector }

    compo.sonata.admin.filter.type.number_range:
        class: Compo\Sonata\AdminBundle\Filter\NumberRangeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_number_range }

    compo.sonata.admin.form.type.number_range:
        class: Compo\Sonata\AdminBundle\Form\Type\NumberRangeType
        tags:
            - { name: form.type, alias: compo_admin_type_number_range }

    compo.sonata.admin.form.type.help:
        class: Compo\Sonata\AdminBundle\Form\Type\HelpType
        parent: compo_core.abstract_container_aware
        tags:
            - { name: form.type, alias: compo_admin_type_help }

    compo.sonata.admin.extension.image:
        class: Compo\Sonata\AdminBundle\Extension\ImageExtension
        tags:
            - { name: sonata.admin.extension, global: true }
        parent: compo_core.abstract_container_aware
