fos_comment:
    db_driver: orm
    class:
        model:
            comment:  Compo\Sonata\CommentBundle\Entity\Comment
            thread:   Compo\Sonata\CommentBundle\Entity\Thread
    form:
        comment:
            type: sonata_comment_comment