fos_elastica:
    clients:
        default:
            host:                               localhost
            port:                               9200

    indexes:
        main:
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                type: snowball
                                language: Russian

            index_name: "%fos_elastica_index_name%"

            client:                             default