services:
    compo_sms_provider.admin.sms_provider:
        class: Compo\SmsProviderBundle\Admin\SmsProviderAdmin
        arguments: [~, Compo\SmsProviderBundle\Entity\SmsProvider, CompoSmsProviderBundle:SmsProviderAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, trash: true, audit: true, label: sms_provider }

    compo_sms_provider.manager.sms_provider:
        class: Compo\SmsProviderBundle\Manager\SmsProviderManager
        arguments: [Compo\SmsProviderBundle\Entity\SmsProvider, "@doctrine"]
        parent: compo_core.abstract_container_aware